'use server';
/**
 * @fileOverview Generates solutions from user prompts using a large language model.
 *
 * - generateSolutions - A function that takes a user prompt and returns potential solutions.
 * - GenerateSolutionsInput - The input type for the generateSolutions function.
 * - GenerateSolutionsOutput - The return type for the generateSolutions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSolutionsInputSchema = z.object({
  prompt: z.string().describe('The user prompt describing the problem.'),
});
export type GenerateSolutionsInput = z.infer<typeof GenerateSolutionsInputSchema>;

const GenerateSolutionsOutputSchema = z.object({
  solutions: z.array(z.string()).describe('An array of potential solutions generated by the AI model.'),
});
export type GenerateSolutionsOutput = z.infer<typeof GenerateSolutionsOutputSchema>;

export async function generateSolutions(input: GenerateSolutionsInput): Promise<GenerateSolutionsOutput> {
  return generateSolutionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSolutionsPrompt',
  input: {schema: GenerateSolutionsInputSchema},
  output: {schema: GenerateSolutionsOutputSchema},
  prompt: `You are an AI assistant designed to generate potential solutions to user problems.

  User Problem: {{{prompt}}}

  Generate a list of potential solutions to the problem. Provide at least 3 different solutions.
  Format each solution as a concise statement.
  Solutions:
  `,
});

const generateSolutionsFlow = ai.defineFlow(
  {
    name: 'generateSolutionsFlow',
    inputSchema: GenerateSolutionsInputSchema,
    outputSchema: GenerateSolutionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
