'use server';
/**
 * @fileOverview A flow to improve solutions based on user feedback.
 *
 * - improveSolutionsBasedOnFeedback - A function that improves solutions based on user feedback.
 * - ImproveSolutionsBasedOnFeedbackInput - The input type for the improveSolutionsBasedOnFeedback function.
 * - ImproveSolutionsBasedOnFeedbackOutput - The return type for the improveSolutionsBasedOnFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveSolutionsBasedOnFeedbackInputSchema = z.object({
  prompt: z.string().describe('The original prompt submitted by the user.'),
  generatedSolution: z.string().describe('The solution generated by the AI.'),
  feedback: z.string().describe('User feedback on the generated solution.'),
});
export type ImproveSolutionsBasedOnFeedbackInput = z.infer<typeof ImproveSolutionsBasedOnFeedbackInputSchema>;

const ImproveSolutionsBasedOnFeedbackOutputSchema = z.object({
  improvedSolution: z.string().describe('The improved solution based on the feedback.'),
});
export type ImproveSolutionsBasedOnFeedbackOutput = z.infer<typeof ImproveSolutionsBasedOnFeedbackOutputSchema>;

export async function improveSolutionsBasedOnFeedback(input: ImproveSolutionsBasedOnFeedbackInput): Promise<ImproveSolutionsBasedOnFeedbackOutput> {
  return improveSolutionsBasedOnFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveSolutionsBasedOnFeedbackPrompt',
  input: {schema: ImproveSolutionsBasedOnFeedbackInputSchema},
  output: {schema: ImproveSolutionsBasedOnFeedbackOutputSchema},
  prompt: `You are an AI assistant that improves solutions based on user feedback.

  Original Prompt: {{{prompt}}}
  Generated Solution: {{{generatedSolution}}}
  Feedback: {{{feedback}}}

  Based on the user feedback, provide an improved solution:
  `,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const improveSolutionsBasedOnFeedbackFlow = ai.defineFlow(
  {
    name: 'improveSolutionsBasedOnFeedbackFlow',
    inputSchema: ImproveSolutionsBasedOnFeedbackInputSchema,
    outputSchema: ImproveSolutionsBasedOnFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
