import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Premium Brake Pads',
    price: 55,
    country: 'Germany',
    type: 'Brakes',
    imageId: 'product-1',
    brand: 'Bosch',
    description: 'High-performance ceramic brake pads for superior stopping power and low dust. Engineered for a quiet and smooth braking experience.',
  },
  {
    id: 2,
    name: 'Synthetic Oil Filter',
    price: 18,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-2',
    brand: 'Mobil 1',
    description: 'Advanced synthetic fiber media provides outstanding filtration and protection for your engine. Designed for long maintenance intervals.',
  },
  {
    id: 3,
    name: 'Performance Air Filter',
    price: 30,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-3',
    brand: 'K&N',
    description: 'Washable and reusable high-flow air filter designed to increase horsepower and acceleration. Lasts up to 50,000 miles before cleaning.',
  },
  {
    id: 4,
    name: 'Iridium Spark Plugs (4-Pack)',
    price: 45,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-4',
    brand: 'NGK',
    description: 'Fine wire Iridium tip ensures high durability and a consistently stable spark. Provides better fuel efficiency and throttle response.',
  },
  {
    id: 5,
    name: 'Full Suspension Kit',
    price: 350,
    country: 'Germany',
    type: 'Suspension',
    imageId: 'product-5',
    brand: 'Bilstein',
    description: 'Complete suspension overhaul kit including shocks, struts, and springs. Restores original ride comfort and handling dynamics.',
  },
  {
    id: 6,
    name: 'LED Headlight Bulbs (Pair)',
    price: 90,
    country: 'China',
    type: 'Lighting',
    imageId: 'product-6',
    brand: 'Philips',
    description: 'Upgrade your visibility with these ultra-bright LED headlight bulbs. Crisp white light for a modern look and enhanced safety.',
  },
  {
    id: 7,
    name: 'Drilled & Slotted Brake Rotor',
    price: 95,
    country: 'USA',
    type: 'Brakes',
    imageId: 'product-7',
    brand: 'Power Stop',
    description: 'Precision-drilled holes for maximum heat dissipation and slotted to sweep away gas and dust. Ideal for performance driving.',
  },
  {
    id: 8,
    name: 'AGM Car Battery',
    price: 180,
    country: 'South Korea',
    type: 'Electrical',
    imageId: 'product-8',
    brand: 'Optima',
    description: 'Absorbent Glass Mat (AGM) battery with high cranking power and extreme vibration resistance. Spill-proof and maintenance-free.',
  },
  {
    id: 9,
    name: 'Aluminum Radiator',
    price: 220,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-9',
    brand: 'Mishimoto',
    description: 'TIG-welded aluminum radiator provides a significant improvement in cooling efficiency over stock. A must for tuned and performance vehicles.',
  },
  {
    id: 10,
    name: 'High-Output Alternator',
    price: 250,
    country: 'USA',
    type: 'Electrical',
    imageId: 'product-10',
    brand: 'Mechman',
    description: 'Delivers reliable, high-amperage power for vehicles with significant electrical demands like audio systems or auxiliary lighting.',
  },
  {
    id: 11,
    name: 'High-Flow Fuel Pump',
    price: 130,
    country: 'Germany',
    type: 'Engine',
    imageId: 'product-11',
    brand: 'Walbro',
    description: 'Supports high horsepower applications by delivering more fuel at higher pressures than standard pumps. E85 compatible.',
  },
  {
    id: 12,
    name: 'Engine Water Pump',
    price: 80,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-12',
    brand: 'Aisin',
    description: 'OEM quality water pump designed for efficient coolant circulation to maintain optimal engine temperature. Includes gasket.',
  },
  {
    id: 13,
    name: 'Adjustable Coilover Shock Absorber',
    price: 280,
    country: 'Taiwan',
    type: 'Suspension',
    imageId: 'product-13',
    brand: 'TEIN',
    description: 'Adjustable coilover for ride height and damping. Perfect for enthusiasts looking to fine-tune their vehicle\'s stance and handling.',
  },
  {
    id: 14,
    name: 'Timing Belt Kit with Water Pump',
    price: 190,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-14',
    brand: 'Gates',
    description: 'Complete timing belt service kit including the belt, tensioner, pulleys, and a matching water pump for a full refresh.',
  },
  {
    id: 15,
    name: 'Stage 2 Clutch Kit',
    price: 450,
    country: 'USA',
    type: 'Transmission',
    imageId: 'product-15',
    brand: 'Clutch Masters',
    description: 'Performance clutch kit designed for spirited street driving and occasional track use. Offers increased torque capacity and feel.',
  },
  {
    id: 16,
    name: 'Stainless Steel Cat-Back Exhaust',
    price: 650,
    country: 'USA',
    type: 'Exhaust',
    imageId: 'product-16',
    brand: 'MagnaFlow',
    description: 'Mandrel-bent stainless steel exhaust system for increased flow and a deep, aggressive tone. Polished tips for a premium look.',
  },
  {
    id: 17,
    name: 'High-Flow Catalytic Converter',
    price: 320,
    country: 'USA',
    type: 'Exhaust',
    imageId: 'product-17',
    brand: 'Flowmaster',
    description: 'Universal high-flow catalytic converter designed to maximize exhaust flow while meeting emission standards.',
  },
  {
    id: 18,
    name: 'Wideband Oxygen Sensor Kit',
    price: 170,
    country: 'Germany',
    type: 'Sensors',
    imageId: 'product-18',
    brand: 'Bosch',
    description: 'Essential for engine tuning, this wideband O2 sensor provides precise air-fuel ratio readings to optimize performance and economy.',
  },
  {
    id: 19,
    name: 'Performance Ignition Coil Pack',
    price: 110,
    country: 'USA',
    type: 'Electrical',
    imageId: 'product-19',
    brand: 'MSD',
    description: 'Upgraded ignition coils that deliver higher spark energy for improved combustion, leading to better performance and throttle response.',
  },
  {
    id: 20,
    name: 'Power Steering Pump',
    price: 150,
    country: 'Germany',
    type: 'Steering',
    imageId: 'product-20',
    brand: 'ZF',
    description: 'OEM-quality power steering pump to restore smooth and effortless steering. A direct replacement for a leaking or failing unit.',
  },
  {
    id: 21,
    name: 'Radiator for Ford F150/F200',
    price: 28.87,
    country: 'USA',
    type: 'Radiator',
    imageId: 'product-21',
    brand: 'Generic',
    description: 'Radiator - Ref: F2TZ8005DA. Fits Ford F150/F200.',
  },
  {
    id: 22,
    name: 'Radiator for Ford Fiesta VI 08-',
    price: 25.11,
    country: 'Germany',
    type: 'Radiator',
    imageId: 'product-22',
    brand: 'Generic',
    description: 'Radiator - Ref: 8V518005DG. Fits Ford Fiesta VI 2008 and later.',
  },
  {
    id: 23,
    name: 'Radiator for Honda Civic 92-00',
    price: 15.39,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-23',
    brand: 'Generic',
    description: 'Radiator - Ref: 19010-P08-003 / R1290. Fits Honda Civic 1992-2000.',
  },
  {
    id: 24,
    name: 'Radiator for Honda CR-V 02-05',
    price: 26.73,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-24',
    brand: 'Generic',
    description: 'Radiator - Ref: 19010-PPA-A51 / R2443. Fits Honda CR-V 2002-2005.',
  },
  {
    id: 25,
    name: 'Radiator for Honda CR-V 12-16',
    price: 24.01,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-25',
    brand: 'Generic',
    description: 'Radiator - Ref: 19010-R5A-A01 / R13314. Fits Honda CR-V 2012-2016.',
  },
  {
    id: 26,
    name: 'Radiator for Hyundai Santa Fe 10-14',
    price: 26.73,
    country: 'South Korea',
    type: 'Radiator',
    imageId: 'product-26',
    brand: 'Generic',
    description: 'Radiator - Ref: 25310-1V200 / R13194. Fits Hyundai Santa Fe 2010-2014.',
  },
  {
    id: 27,
    name: 'Radiator for Hyundai Sonata N20 05-10',
    price: 25.56,
    country: 'South Korea',
    type: 'Radiator',
    imageId: 'product-27',
    brand: 'Generic',
    description: 'Radiator - Ref: 25310-3K240 / R2832. Fits Hyundai Sonata N20 2005-2010.',
  },
  {
    id: 28,
    name: 'Radiator for Hyundai Sonata Y20 11-16',
    price: 25.56,
    country: 'South Korea',
    type: 'Radiator',
    imageId: 'product-28',
    brand: 'Generic',
    description: 'Radiator - Ref: 25310-3R500 / R1319. Fits Hyundai Sonata Y20 2011-2016.',
  },
  {
    id: 29,
    name: 'Radiator for Hyundai Tucson 05-09',
    price: 25.56,
    country: 'South Korea',
    type: 'Radiator',
    imageId: 'product-29',
    brand: 'Generic',
    description: 'Radiator - Ref: 25310-2E400 / R2786. Fits Hyundai Tucson 2005-2009.',
  },
  {
    id: 30,
    name: 'Radiator for Hyundai Tucson 10-15',
    price: 25.56,
    country: 'South Korea',
    type: 'Radiator',
    imageId: 'product-30',
    brand: 'Generic',
    description: 'Radiator - Ref: 25310-2S550 / 13150. Fits Hyundai Tucson 2010-2015.',
  },
  {
    id: 31,
    name: 'Radiator for Nissan D21 92-07',
    price: 30.77,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-31',
    brand: 'Generic',
    description: 'Radiator - Ref: 21460-86G10 / R0314. Fits Nissan D21 1992-2007.',
  },
  {
    id: 32,
    name: 'Radiator for Nissan Frontier 98-04',
    price: 27.04,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-32',
    brand: 'Generic',
    description: 'Radiator - Ref: 21460-3S100. Fits Nissan Frontier (Motor Qd32) 1998-2004.',
  },
  {
    id: 33,
    name: 'Radiator for Nissan Navara 05-07',
    price: 32.54,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-33',
    brand: 'Generic',
    description: 'Radiator - Ref: 21460-EB30A / R2808. Fits Nissan Navara 2005-2007.',
  },
  {
    id: 34,
    name: 'Radiator for Toyota Corolla 03-08',
    price: 23.49,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-34',
    brand: 'Generic',
    description: 'Radiator - Ref: 16400-0D240 / R2428. Fits Toyota Corolla 2003-2008.',
  },
  {
    id: 35,
    name: 'Radiator for Toyota Corolla 09-13',
    price: 23.49,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-35',
    brand: 'Generic',
    description: 'Radiator - Ref: 16400-22180 / R13106. Fits Toyota Corolla 2009-2013.',
  },
  {
    id: 36,
    name: 'Radiator for Toyota Corolla 93-97',
    price: 24.79,
    country: 'Japan',
    type: 'Radiator',
    imageId: 'product-36',
    brand: 'Generic',
    description: 'Radiator - Ref: 16400-16431 / R1409. Fits Toyota Corolla 1993-1997.',
  },
  {
    id: 37,
    name: 'Radiator for Peugeot 1007 04-05',
    price: 16.01,
    country: 'France',
    type: 'Radiator',
    imageId: 'product-37',
    brand: 'Generic',
    description: 'Radiator - Ref: 50467. Fits Peugeot 1007 2004-2005.',
  },
  {
    id: 38,
    name: 'Radiator for Renault Logan I 04-09',
    price: 18.92,
    country: 'France',
    type: 'Radiator',
    imageId: 'product-38',
    brand: 'Generic',
    description: 'Radiator - Ref: 63708A. Fits Renault Logan I 2004-2009.',
  },
  {
    id: 39,
    name: 'Radiator for Renault Logan I 04-09 (Alt)',
    price: 16.27,
    country: 'France',
    type: 'Radiator',
    imageId: 'product-39',
    brand: 'Generic',
    description: 'Radiator - Ref: 8200735038. Fits Renault Logan I 2004-2009.',
  },
  {
    id: 40,
    name: 'Radiator for Citroen Berlingo 02-11',
    price: 18.35,
    country: 'France',
    type: 'Radiator',
    imageId: 'product-40',
    brand: 'Generic',
    description: 'Radiator - Ref: 63502. Fits Citroen Berlingo 2002-2011.',
  },
];

    