import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Premium Brake Pads',
    price: 55,
    country: 'Germany',
    type: 'Brakes',
    imageId: 'product-1',
    brand: 'Bosch',
    description: 'High-performance ceramic brake pads for superior stopping power and low dust. Engineered for a quiet and smooth braking experience.',
  },
  {
    id: 2,
    name: 'Synthetic Oil Filter',
    price: 18,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-2',
    brand: 'Mobil 1',
    description: 'Advanced synthetic fiber media provides outstanding filtration and protection for your engine. Designed for long maintenance intervals.',
  },
  {
    id: 3,
    name: 'Performance Air Filter',
    price: 30,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-3',
    brand: 'K&N',
    description: 'Washable and reusable high-flow air filter designed to increase horsepower and acceleration. Lasts up to 50,000 miles before cleaning.',
  },
  {
    id: 4,
    name: 'Iridium Spark Plugs (4-Pack)',
    price: 45,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-4',
    brand: 'NGK',
    description: 'Fine wire Iridium tip ensures high durability and a consistently stable spark. Provides better fuel efficiency and throttle response.',
  },
  {
    id: 5,
    name: 'Full Suspension Kit',
    price: 350,
    country: 'Germany',
    type: 'Suspension',
    imageId: 'product-5',
    brand: 'Bilstein',
    description: 'Complete suspension overhaul kit including shocks, struts, and springs. Restores original ride comfort and handling dynamics.',
  },
  {
    id: 6,
    name: 'LED Headlight Bulbs (Pair)',
    price: 90,
    country: 'China',
    type: 'Lighting',
    imageId: 'product-6',
    brand: 'Philips',
    description: 'Upgrade your visibility with these ultra-bright LED headlight bulbs. Crisp white light for a modern look and enhanced safety.',
  },
  {
    id: 7,
    name: 'Drilled & Slotted Brake Rotor',
    price: 95,
    country: 'USA',
    type: 'Brakes',
    imageId: 'product-7',
    brand: 'Power Stop',
    description: 'Precision-drilled holes for maximum heat dissipation and slotted to sweep away gas and dust. Ideal for performance driving.',
  },
  {
    id: 8,
    name: 'AGM Car Battery',
    price: 180,
    country: 'South Korea',
    type: 'Electrical',
    imageId: 'product-8',
    brand: 'Optima',
    description: 'Absorbent Glass Mat (AGM) battery with high cranking power and extreme vibration resistance. Spill-proof and maintenance-free.',
  },
  {
    id: 9,
    name: 'Aluminum Radiator',
    price: 220,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-9',
    brand: 'Mishimoto',
    description: 'TIG-welded aluminum radiator provides a significant improvement in cooling efficiency over stock. A must for tuned and performance vehicles.',
  },
  {
    id: 10,
    name: 'High-Output Alternator',
    price: 250,
    country: 'USA',
    type: 'Electrical',
    imageId: 'product-10',
    brand: 'Mechman',
    description: 'Delivers reliable, high-amperage power for vehicles with significant electrical demands like audio systems or auxiliary lighting.',
  },
  {
    id: 11,
    name: 'High-Flow Fuel Pump',
    price: 130,
    country: 'Germany',
    type: 'Engine',
    imageId: 'product-11',
    brand: 'Walbro',
    description: 'Supports high horsepower applications by delivering more fuel at higher pressures than standard pumps. E85 compatible.',
  },
  {
    id: 12,
    name: 'Engine Water Pump',
    price: 80,
    country: 'Japan',
    type: 'Engine',
    imageId: 'product-12',
    brand: 'Aisin',
    description: 'OEM quality water pump designed for efficient coolant circulation to maintain optimal engine temperature. Includes gasket.',
  },
  {
    id: 13,
    name: 'Adjustable Coilover Shock Absorber',
    price: 280,
    country: 'Taiwan',
    type: 'Suspension',
    imageId: 'product-13',
    brand: 'TEIN',
    description: 'Adjustable coilover for ride height and damping. Perfect for enthusiasts looking to fine-tune their vehicle\'s stance and handling.',
  },
  {
    id: 14,
    name: 'Timing Belt Kit with Water Pump',
    price: 190,
    country: 'USA',
    type: 'Engine',
    imageId: 'product-14',
    brand: 'Gates',
    description: 'Complete timing belt service kit including the belt, tensioner, pulleys, and a matching water pump for a full refresh.',
  },
  {
    id: 15,
    name: 'Stage 2 Clutch Kit',
    price: 450,
    country: 'USA',
    type: 'Transmission',
    imageId: 'product-15',
    brand: 'Clutch Masters',
    description: 'Performance clutch kit designed for spirited street driving and occasional track use. Offers increased torque capacity and feel.',
  },
  {
    id: 16,
    name: 'Stainless Steel Cat-Back Exhaust',
    price: 650,
    country: 'USA',
    type: 'Exhaust',
    imageId: 'product-16',
    brand: 'MagnaFlow',
    description: 'Mandrel-bent stainless steel exhaust system for increased flow and a deep, aggressive tone. Polished tips for a premium look.',
  },
  {
    id: 17,
    name: 'High-Flow Catalytic Converter',
    price: 320,
    country: 'USA',
    type: 'Exhaust',
    imageId: 'product-17',
    brand: 'Flowmaster',
    description: 'Universal high-flow catalytic converter designed to maximize exhaust flow while meeting emission standards.',
  },
  {
    id: 18,
    name: 'Wideband Oxygen Sensor Kit',
    price: 170,
    country: 'Germany',
    type: 'Sensors',
    imageId: 'product-18',
    brand: 'Bosch',
    description: 'Essential for engine tuning, this wideband O2 sensor provides precise air-fuel ratio readings to optimize performance and economy.',
  },
  {
    id: 19,
    name: 'Performance Ignition Coil Pack',
    price: 110,
    country: 'USA',
    type: 'Electrical',
    imageId: 'product-19',
    brand: 'MSD',
    description: 'Upgraded ignition coils that deliver higher spark energy for improved combustion, leading to better performance and throttle response.',
  },
  {
    id: 20,
    name: 'Power Steering Pump',
    price: 150,
    country: 'Germany',
    type: 'Steering',
    imageId: 'product-20',
    brand: 'ZF',
    description: 'OEM-quality power steering pump to restore smooth and effortless steering. A direct replacement for a leaking or failing unit.',
  },
];
